export const SIDERBAR_PRODUCT_ID = {
  PRODUCT_1: "PRODUCT_1",
  PRODUCT_2: "PRODUCT_2",
  PRODUCT_3: "PRODUCT_3",
};

export const SIDERBAR_DASHBOARD_ID = {
  DASHBOARD_1: "DASHBOARD_1",
  DASHBOARD_2: "DASHBOARD_2",
};

export const SIDERBAR_ID = {
  DASHBOARD: "DASHBOARD",
  OVERVIEW: "OVERVIEW",
  SIDERBAR_PRODUCT_ID,
  SIDERBAR_DASHBOARD_ID,
  // GAME: "GAME",
  //   SIDERBAR_ASSET_MANAGER_ID,
  //   SIDERBAR_FILE_MANAGER_ID,
  //   SIDERBAR_CATEGORY_ID,
};
